export const LIST_CONTACTS_SUCCESS = 'LIST_CONTACTS_SUCCESS';

export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';

export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';

export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';

export const SEARCH_CONTACTS_SUCCESS = 'SEARCH_CONTACTS_SUCCESS';

export const SELECT_CONTACT_FOR_UPDATE_SUCCESS = 'SELECT_CONTACT_FOR_UPDATE_SUCCESS';